In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data_16=pd.read_csv('C:/Users/good/Desktop/HDSC Internship/Premier Project/archive/cms_hospital_patient_satisfaction_2016.csv')
data_17=pd.read_csv('C:/Users/good/Desktop/HDSC Internship/Premier Project/archive/cms_hospital_patient_satisfaction_2017.csv')
data_18=pd.read_csv('C:/Users/good/Desktop/HDSC Internship/Premier Project/archive/cms_hospital_patient_satisfaction_2018.csv')
data_19=pd.read_csv('C:/Users/good/Desktop/HDSC Internship/Premier Project/archive/cms_hospital_patient_satisfaction_2019.csv')
data_20=pd.read_csv('C:/Users/good/Desktop/HDSC Internship/Premier Project/archive/cms_hospital_patient_satisfaction_2020.csv')

C:\Users\Dullard_boy\.conda\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (14,17,19,26) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\Dullard_boy\.conda\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (0,14,17,19,26) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
data_16=data_16.groupby('County Name')
data_16=data_16.get_group('LOS ANGELES')
word1 = 'Footnote'
word2 = 'footnote'
for i in data_16.columns:
    if word1 in i:
        data_16.drop(i, axis = 1, inplace= True)
    elif word2 in i:
        data_16.drop(i, axis = 1, inplace= True) 
    else:
        pass
data_16.shape

(4510, 31)

In [4]:
data_17=data_17.groupby('County Name')
data_17=data_17.get_group('LOS ANGELES')
word1 = 'Footnote'
word2 = 'footnote'
for i in data_17.columns:
    if word1 in i:
        data_17.drop(i, axis = 1, inplace= True)
    elif word2 in i:
        data_17.drop(i, axis = 1, inplace= True) 
    else:
        pass
data_17.shape

(4565, 31)

In [5]:
data_18=data_18.groupby('County Name')
data_18=data_18.get_group('LOS ANGELES')
word1 = 'Footnote'
word2 = 'footnote'
for i in data_18.columns:
    if word1 in i:
        data_18.drop(i, axis = 1, inplace= True)
    elif word2 in i:
        data_18.drop(i, axis = 1, inplace= True) 
    else:
        pass
data_18.shape

(4100, 31)

In [6]:
data_19=data_19.groupby('County Name')
data_19=data_19.get_group('LOS ANGELES')
word1 = 'Footnote'
word2 = 'footnote'
for i in data_19.columns:
    if word1 in i:
        data_19.drop(i, axis = 1, inplace= True)
    elif word2 in i:
        data_19.drop(i, axis = 1, inplace= True) 
    else:
        pass
data_19.shape

(7440, 31)

In [7]:
data_20=data_20.groupby('County Name')
data_20=data_20.get_group('LOS ANGELES')
word1 = 'Footnote'
word2 = 'footnote'
for i in data_20.columns:
    if word1 in i:
        data_20.drop(i, axis = 1, inplace= True)
    elif word2 in i:
        data_20.drop(i, axis = 1, inplace= True) 
    else:
        pass
data_20.shape

(7347, 31)

In [8]:
data_16.columns

Index(['Facility ID', 'Facility Name', 'Address', 'City', 'State', 'ZIP Code',
       'County Name', 'Phone Number', 'HCAHPS Measure ID', 'HCAHPS Question',
       'HCAHPS Answer Description', 'Patient Survey Star Rating',
       'HCAHPS Answer Percent', 'HCAHPS Linear Mean Value',
       'Number of Completed Surveys', 'Survey Response Rate Percent',
       'Start Date', 'End Date', 'Year', 'Hospital Type', 'Hospital Ownership',
       'Emergency Services',
       'Meets criteria for promoting interoperability of EHRs',
       'Hospital overall rating', 'Mortality national comparison',
       'Safety of care national comparison', 'Readmission national comparison',
       'Patient experience national comparison',
       'Effectiveness of care national comparison',
       'Timeliness of care national comparison',
       'Efficient use of medical imaging national comparison'],
      dtype='object')

In [9]:
rating={'Not Available':0,'Below the National average':1,'Same as the National average':2,'Above the National average':3}
data_16['Mortality national comparison'].replace(rating, inplace=True)
data_16['Safety of care national comparison'].replace(rating, inplace=True)
data_16['Readmission national comparison'].replace(rating, inplace=True)
data_16['Patient experience national comparison'].replace(rating, inplace=True)
data_16['Effectiveness of care national comparison'].replace(rating, inplace=True)
data_16['Timeliness of care national comparison'].replace(rating, inplace=True)
data_16['Efficient use of medical imaging national comparison'].replace(rating, inplace=True)

In [10]:
data_16['Hospital overall rating'].replace('Not Available',0, inplace=True)

In [11]:
data_16['Patient Survey Star Rating'].replace('Not Available',0, inplace=True)
data_16['Patient Survey Star Rating'].replace('Not Applicable',0, inplace=True)

In [12]:
data_16['Hospital overall rating']=pd.to_numeric(data_16['Hospital overall rating'])
data_16['Patient Survey Star Rating']=pd.to_numeric(data_16['Patient Survey Star Rating'])

In [18]:
hospital_rating_16=data_16[['Facility Name','Hospital overall rating','Mortality national comparison','Safety of care national comparison', 'Readmission national comparison','Patient experience national comparison','Effectiveness of care national comparison','Timeliness of care national comparison','Efficient use of medical imaging national comparison']].groupby('Facility Name').mean()

In [19]:
for i in hospital_rating_16.columns:
    print(hospital_rating_16[i].value_counts())

3    38
2    19
4    14
0     9
5     1
1     1
Name: Hospital overall rating, dtype: int64
3    35
2    28
0    18
1     1
Name: Mortality national comparison, dtype: int64
2    35
3    23
1    13
0    11
Name: Safety of care national comparison, dtype: int64
2    28
1    26
0    16
3    12
Name: Readmission national comparison, dtype: int64
1    51
2    16
0    10
3     5
Name: Patient experience national comparison, dtype: int64
2    61
1    11
0     8
3     2
Name: Effectiveness of care national comparison, dtype: int64
1    41
2    21
0    17
3     3
Name: Timeliness of care national comparison, dtype: int64
0    42
2    31
1     7
3     2
Name: Efficient use of medical imaging national comparison, dtype: int64

In [20]:
hospital_rating_per_city_16=data_16[['City','Hospital overall rating','Mortality national comparison','Safety of care national comparison', 'Readmission national comparison','Patient experience national comparison','Effectiveness of care national comparison','Timeliness of care national comparison','Efficient use of medical imaging national comparison']].groupby('City').mean()
hospital_rating_per_city_16=hospital_rating_per_city_16.round(0)

In [21]:
for i in hospital_rating_per_city_16.columns:
    print(hospital_rating_per_city_16[i].value_counts())

3.0    22
2.0    13
4.0     8
0.0     2
1.0     1
5.0     1
Name: Hospital overall rating, dtype: int64
2.0    19
3.0    19
0.0     6
1.0     3
Name: Mortality national comparison, dtype: int64
2.0    20
3.0    15
1.0     9
0.0     3
Name: Safety of care national comparison, dtype: int64
2.0    17
1.0    17
3.0     7
0.0     6
Name: Readmission national comparison, dtype: int64
1.0    30
2.0    14
0.0     2
3.0     1
Name: Patient experience national comparison, dtype: int64
2.0    35
1.0     9
0.0     2
3.0     1
Name: Effectiveness of care national comparison, dtype: int64
1.0    26
2.0    12
0.0     6
3.0     3
Name: Timeliness of care national comparison, dtype: int64
0.0    21
2.0    20
1.0     5
3.0     1
Name: Efficient use of medical imaging national comparison, dtype: int64

In [46]:
hospital_rating_per_city_16.loc[hospital_rating_per_city_16['Hospital overall rating'] == 5]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
City,,,,,,,,
ARCADIA,5.0,3.0,3.0,3.0,2.0,2.0,2.0,3.0

In [47]:
hospital_rating_per_city_16.loc[hospital_rating_per_city_16['Hospital overall rating'] == 1]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
City,,,,,,,,
LANCASTER,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0

In [22]:
hospital_rating_16.loc[hospital_rating_16['Hospital overall rating'] == 5]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
Facility Name,,,,,,,,
METHODIST HOSPITAL OF SOUTHERN CA,5,3,3,3,2,2,2,3

In [23]:
hospital_rating_16.loc[hospital_rating_16['Hospital overall rating'] == 1]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
Facility Name,,,,,,,,
ANTELOPE VALLEY HOSPITAL,1,1,1,2,1,2,1,2

In [24]:
rating={'Not Available':0,'Below the national average':1,'Same as the national average':2,'Above the national average':3}
data_17['Mortality national comparison'].replace(rating, inplace=True)
data_17['Safety of care national comparison'].replace(rating, inplace=True)
data_17['Readmission national comparison'].replace(rating, inplace=True)
data_17['Patient experience national comparison'].replace(rating, inplace=True)
data_17['Effectiveness of care national comparison'].replace(rating, inplace=True)
data_17['Timeliness of care national comparison'].replace(rating, inplace=True)
data_17['Efficient use of medical imaging national comparison'].replace(rating, inplace=True)

In [25]:
data_17['Hospital overall rating'].replace('Not Available',0, inplace=True)
data_17['Patient Survey Star Rating'].replace('Not Available',0, inplace=True)
data_17['Patient Survey Star Rating'].replace('Not Applicable',0, inplace=True)
data_17['Hospital overall rating']=pd.to_numeric(data_17['Hospital overall rating'])
data_17['Patient Survey Star Rating']=pd.to_numeric(data_17['Patient Survey Star Rating'])

In [26]:
hospital_rating_per_city_17=data_17[['City','Hospital overall rating','Mortality national comparison','Safety of care national comparison', 'Readmission national comparison','Patient experience national comparison','Effectiveness of care national comparison','Timeliness of care national comparison','Efficient use of medical imaging national comparison']].groupby('City').mean()
hospital_rating_per_city_17=hospital_rating_per_city_17.round(0)
for i in hospital_rating_per_city_17.columns:
    print(hospital_rating_per_city_17[i].value_counts())

3.0    21
2.0    14
4.0     8
0.0     2
1.0     1
5.0     1
Name: Hospital overall rating, dtype: int64
3.0    19
2.0    18
0.0     6
1.0     4
Name: Mortality national comparison, dtype: int64
2.0    19
3.0    15
1.0    10
0.0     3
Name: Safety of care national comparison, dtype: int64
1.0    18
2.0    16
3.0     7
0.0     6
Name: Readmission national comparison, dtype: int64
1.0    31
2.0    13
0.0     2
3.0     1
Name: Patient experience national comparison, dtype: int64
2.0    34
1.0    10
0.0     2
3.0     1
Name: Effectiveness of care national comparison, dtype: int64
1.0    25
2.0    12
0.0     7
3.0     3
Name: Timeliness of care national comparison, dtype: int64
0.0    21
2.0    19
1.0     6
3.0     1
Name: Efficient use of medical imaging national comparison, dtype: int64

In [48]:
hospital_rating_per_city_17.loc[hospital_rating_per_city_17['Hospital overall rating'] == 5]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
City,,,,,,,,
ARCADIA,5.0,3.0,3.0,3.0,2.0,2.0,2.0,3.0

In [49]:
hospital_rating_per_city_17.loc[hospital_rating_per_city_17['Hospital overall rating'] == 1]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
City,,,,,,,,
LANCASTER,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0

In [27]:
hospital_rating_per_city_17.shape

(47, 8)

In [28]:
hospital_rating_17=data_17[['Facility Name','Hospital overall rating','Mortality national comparison','Safety of care national comparison', 'Readmission national comparison','Patient experience national comparison','Effectiveness of care national comparison','Timeliness of care national comparison','Efficient use of medical imaging national comparison']].groupby('Facility Name').mean()
hospital_rating_17=hospital_rating_17.round(0)
for i in hospital_rating_17.columns:
    print(hospital_rating_17[i].value_counts())

3    38
2    19
4    14
0    10
5     1
1     1
Name: Hospital overall rating, dtype: int64
3    35
2    28
0    19
1     1
Name: Mortality national comparison, dtype: int64
2    35
3    23
1    13
0    12
Name: Safety of care national comparison, dtype: int64
2    28
1    26
0    17
3    12
Name: Readmission national comparison, dtype: int64
1    51
2    16
0    11
3     5
Name: Patient experience national comparison, dtype: int64
2    61
1    11
0     9
3     2
Name: Effectiveness of care national comparison, dtype: int64
1    41
2    21
0    18
3     3
Name: Timeliness of care national comparison, dtype: int64
0    43
2    31
1     7
3     2
Name: Efficient use of medical imaging national comparison, dtype: int64

In [29]:
hospital_rating_17.loc[hospital_rating_17['Hospital overall rating'] == 5]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
Facility Name,,,,,,,,
METHODIST HOSPITAL OF SOUTHERN CA,5,3,3,3,2,2,2,3

In [30]:
hospital_rating_17.loc[hospital_rating_17['Hospital overall rating'] == 1]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
Facility Name,,,,,,,,
ANTELOPE VALLEY HOSPITAL,1,1,1,2,1,2,1,2

In [31]:
rating={'Not Available':0,'Below the national average':1,'Same as the national average':2,'Above the national average':3}
data_18['Mortality national comparison'].replace(rating, inplace=True)
data_18['Safety of care national comparison'].replace(rating, inplace=True)
data_18['Readmission national comparison'].replace(rating, inplace=True)
data_18['Patient experience national comparison'].replace(rating, inplace=True)
data_18['Effectiveness of care national comparison'].replace(rating, inplace=True)
data_18['Timeliness of care national comparison'].replace(rating, inplace=True)
data_18['Efficient use of medical imaging national comparison'].replace(rating, inplace=True)
data_18['Hospital overall rating'].replace('Not Available',0, inplace=True)
data_18['Patient Survey Star Rating'].replace('Not Available',0, inplace=True)
data_18['Patient Survey Star Rating'].replace('Not Applicable',0, inplace=True)
data_18['Hospital overall rating']=pd.to_numeric(data_18['Hospital overall rating'])
data_18['Patient Survey Star Rating']=pd.to_numeric(data_18['Patient Survey Star Rating'])

In [32]:
hospital_rating_per_city_18=data_18[['City','Hospital overall rating','Mortality national comparison','Safety of care national comparison', 'Readmission national comparison','Patient experience national comparison','Effectiveness of care national comparison','Timeliness of care national comparison','Efficient use of medical imaging national comparison']].groupby('City').mean()
hospital_rating_per_city_18=hospital_rating_per_city_18.round(0)
for i in hospital_rating_per_city_18.columns:
    print(hospital_rating_per_city_18[i].value_counts())

2.0    14
4.0    11
3.0     9
1.0     8
0.0     2
5.0     2
Name: Hospital overall rating, dtype: int64
2.0    20
3.0    15
0.0     7
1.0     4
Name: Mortality national comparison, dtype: int64
2.0    18
3.0    13
1.0    10
0.0     5
Name: Safety of care national comparison, dtype: int64
1.0    26
2.0     9
0.0     7
3.0     4
Name: Readmission national comparison, dtype: int64
1.0    28
2.0    14
0.0     3
3.0     1
Name: Patient experience national comparison, dtype: int64
2.0    34
1.0    10
0.0     2
Name: Effectiveness of care national comparison, dtype: int64
1.0    24
2.0    10
0.0     8
3.0     4
Name: Timeliness of care national comparison, dtype: int64
0.0    21
2.0    15
1.0     6
3.0     4
Name: Efficient use of medical imaging national comparison, dtype: int64

In [50]:
hospital_rating_per_city_18.loc[hospital_rating_per_city_18['Hospital overall rating'] == 5]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
City,,,,,,,,
ARCADIA,5.0,3.0,3.0,3.0,2.0,2.0,1.0,3.0
PASADENA,5.0,3.0,3.0,2.0,2.0,1.0,1.0,2.0

In [51]:
hospital_rating_per_city_18.loc[hospital_rating_per_city_18['Hospital overall rating'] == 1]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
City,,,,,,,,
BURBANK,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0
COVINA,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0
GARDENA,1.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0
HUNTINGTON PARK,1.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0
LANCASTER,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0
NORTHRIDGE,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0
POMONA,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
VAN NUYS,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0

In [33]:
hospital_rating_18=data_18[['Facility Name','Hospital overall rating','Mortality national comparison','Safety of care national comparison', 'Readmission national comparison','Patient experience national comparison','Effectiveness of care national comparison','Timeliness of care national comparison','Efficient use of medical imaging national comparison']].groupby('Facility Name').mean()
hospital_rating_18=hospital_rating_18.round(0)
for i in hospital_rating_18.columns:
    print(hospital_rating_18[i].value_counts())

2    24
4    18
3    17
0     9
1     8
5     6
Name: Hospital overall rating, dtype: int64
3    32
2    29
0    20
1     1
Name: Mortality national comparison, dtype: int64
3    31
2    23
1    18
0    10
Name: Safety of care national comparison, dtype: int64
1    44
0    16
3    12
2    10
Name: Readmission national comparison, dtype: int64
1    48
2    18
0    10
3     6
Name: Patient experience national comparison, dtype: int64
2    62
1    11
0     9
Name: Effectiveness of care national comparison, dtype: int64
1    45
0    18
2    14
3     5
Name: Timeliness of care national comparison, dtype: int64
0    44
2    28
3     5
1     5
Name: Efficient use of medical imaging national comparison, dtype: int64

In [34]:
hospital_rating_18.loc[hospital_rating_18['Hospital overall rating'] == 5]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
Facility Name,,,,,,,,
CEDARS-SINAI MEDICAL CENTER,5,3,2,2,2,2,1,3
HUNTINGTON MEMORIAL HOSPITAL,5,3,3,2,2,1,1,2
METHODIST HOSPITAL OF SOUTHERN CA,5,3,3,3,2,2,1,3
SANTA MONICA - UCLA MED CTR & ORTHOPAEDIC HOSPITAL,5,3,3,1,3,2,1,2
SILVER LAKE MEDICAL CENTER,5,3,3,2,0,2,0,0
TORRANCE MEMORIAL MEDICAL CENTER,5,2,3,3,3,2,1,2

In [35]:
hospital_rating_18.loc[hospital_rating_18['Hospital overall rating'] == 1]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
Facility Name,,,,,,,,
ANTELOPE VALLEY HOSPITAL,1,1,1,1,1,1,1,3
CITRUS VALLEY MEDICAL CENTER-IC CAMPUS,1,3,1,1,1,1,1,1
COMMUNITY HOSPITAL OF HUNTINGTON PARK,1,2,0,1,1,1,1,0
MEMORIAL HOSPITAL OF GARDENA,1,2,1,1,1,1,1,0
NORTHRIDGE HOSPITAL MEDICAL CENTER,1,2,1,1,1,2,1,2
PROVIDENCE SAINT JOSEPH MEDICAL CTR,1,2,1,1,1,2,2,2
USC VERDUGO HILLS HOSPITAL,1,2,1,1,1,2,1,2
VALLEY PRESBYTERIAN HOSPITAL,1,2,1,1,1,1,1,2

In [36]:
rating={'Not Available':0,'Below the national average':1,'Same as the national average':2,'Above the national average':3}
data_19['Mortality national comparison'].replace(rating, inplace=True)
data_19['Safety of care national comparison'].replace(rating, inplace=True)
data_19['Readmission national comparison'].replace(rating, inplace=True)
data_19['Patient experience national comparison'].replace(rating, inplace=True)
data_19['Effectiveness of care national comparison'].replace(rating, inplace=True)
data_19['Timeliness of care national comparison'].replace(rating, inplace=True)
data_19['Efficient use of medical imaging national comparison'].replace(rating, inplace=True)
data_19['Hospital overall rating'].replace('Not Available',0, inplace=True)
data_19['Patient Survey Star Rating'].replace('Not Available',0, inplace=True)
data_19['Patient Survey Star Rating'].replace('Not Applicable',0, inplace=True)
data_19['Hospital overall rating']=pd.to_numeric(data_19['Hospital overall rating'])
data_19['Patient Survey Star Rating']=pd.to_numeric(data_19['Patient Survey Star Rating'])

In [37]:
hospital_rating_per_city_19=data_19[['City','Hospital overall rating','Mortality national comparison','Safety of care national comparison', 'Readmission national comparison','Patient experience national comparison','Effectiveness of care national comparison','Timeliness of care national comparison','Efficient use of medical imaging national comparison']].groupby('City').mean()
hospital_rating_per_city_19=hospital_rating_per_city_19.round(0)
for i in hospital_rating_per_city_19.columns:
    print(hospital_rating_per_city_19[i].value_counts())

2.0    18
3.0    12
4.0    12
1.0     2
0.0     2
Name: Hospital overall rating, dtype: int64
2.0    19
3.0    16
0.0     7
1.0     4
Name: Mortality national comparison, dtype: int64
2.0    16
1.0    14
3.0    12
0.0     4
Name: Safety of care national comparison, dtype: int64
1.0    24
2.0    11
3.0     6
0.0     5
Name: Readmission national comparison, dtype: int64
1.0    27
2.0    11
3.0     5
0.0     3
Name: Patient experience national comparison, dtype: int64
2.0    36
1.0     8
0.0     2
Name: Effectiveness of care national comparison, dtype: int64
1.0    26
2.0     9
0.0     8
3.0     3
Name: Timeliness of care national comparison, dtype: int64
2.0    17
0.0    17
1.0     6
3.0     6
Name: Efficient use of medical imaging national comparison, dtype: int64

In [52]:
hospital_rating_per_city_19.loc[hospital_rating_per_city_19['Hospital overall rating'] == 5]

Empty DataFrame
Columns: [Hospital overall rating, Mortality national comparison, Safety of care national comparison, Readmission national comparison, Patient experience national comparison, Effectiveness of care national comparison, Timeliness of care national comparison, Efficient use of medical imaging national comparison]
Index: []

In [53]:
hospital_rating_per_city_19.loc[hospital_rating_per_city_19['Hospital overall rating'] == 1]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
City,,,,,,,,
GARDENA,1.0,2.0,1.0,1.0,1.0,1.0,2.0,0.0
LANCASTER,1.0,1.0,1.0,1.0,1.0,2.0,1.0,3.0

In [38]:
hospital_rating_19=data_19[['Facility Name','Hospital overall rating','Mortality national comparison','Safety of care national comparison', 'Readmission national comparison','Patient experience national comparison','Effectiveness of care national comparison','Timeliness of care national comparison','Efficient use of medical imaging national comparison']].groupby('Facility Name').mean()
hospital_rating_19=hospital_rating_19.round(0)
for i in hospital_rating_19.columns:
    print(hospital_rating_19[i].value_counts())

2    28
3    21
4    18
0     6
1     4
5     3
Name: Hospital overall rating, dtype: int64
3    32
2    29
0    18
1     1
Name: Mortality national comparison, dtype: int64
3    28
1    28
2    16
0     8
Name: Safety of care national comparison, dtype: int64
1    44
3    15
0    12
2     9
Name: Readmission national comparison, dtype: int64
1    44
2    16
3    11
0     9
Name: Patient experience national comparison, dtype: int64
2    60
1    12
0     7
3     1
Name: Effectiveness of care national comparison, dtype: int64
1    45
0    17
2    14
3     4
Name: Timeliness of care national comparison, dtype: int64
0    38
2    29
3     8
1     5
Name: Efficient use of medical imaging national comparison, dtype: int64

In [39]:
hospital_rating_19.loc[hospital_rating_19['Hospital overall rating'] == 5]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
Facility Name,,,,,,,,
CEDARS-SINAI MEDICAL CENTER,5,3,1,3,3,2,1,3
GLENDORA COMMUNITY HOSPITAL,5,2,0,3,0,2,2,0
SANTA MONICA - UCLA MED CTR & ORTHOPAEDIC HOSPITAL,5,3,3,1,2,2,1,2

In [40]:
hospital_rating_19.loc[hospital_rating_19['Hospital overall rating'] == 1]

,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
Facility Name,,,,,,,,
ANTELOPE VALLEY HOSPITAL,1,1,1,1,1,2,1,3
HOLLYWOOD PRESBYTERIAN MEDICAL CENTER,1,3,1,1,1,2,2,2
LAC+USC MEDICAL CENTER,1,2,1,1,1,2,1,0
MEMORIAL HOSPITAL OF GARDENA,1,2,1,1,1,1,2,0

In [41]:
rating={'Not Available':0,'Below the national average':1,'Same as the national average':2,'Above the national average':3}
data_20['Mortality national comparison'].replace(rating, inplace=True)
data_20['Safety of care national comparison'].replace(rating, inplace=True)
data_20['Readmission national comparison'].replace(rating, inplace=True)
data_20['Patient experience national comparison'].replace(rating, inplace=True)
data_20['Effectiveness of care national comparison'].replace(rating, inplace=True)
data_20['Timeliness of care national comparison'].replace(rating, inplace=True)
data_20['Efficient use of medical imaging national comparison'].replace(rating, inplace=True)
data_20['Hospital overall rating'].replace('Not Available',0, inplace=True)
data_20['Patient Survey Star Rating'].replace('Not Available',0, inplace=True)
data_20['Patient Survey Star Rating'].replace('Not Applicable',0, inplace=True)
data_20['Hospital overall rating']=pd.to_numeric(data_19['Hospital overall rating'])
data_20['Patient Survey Star Rating']=pd.to_numeric(data_19['Patient Survey Star Rating'])

In [42]:
hospital_rating_per_city_20=data_20[['City','Hospital overall rating','Mortality national comparison','Safety of care national comparison', 'Readmission national comparison','Patient experience national comparison','Effectiveness of care national comparison','Timeliness of care national comparison','Efficient use of medical imaging national comparison']].groupby('City').mean()
hospital_rating_per_city_20=hospital_rating_per_city_20.round(0)
for i in hospital_rating_per_city_20.columns:
    print(hospital_rating_per_city_20[i].value_counts())

2.0    7
4.0    5
3.0    5
0.0    1
Name: Hospital overall rating, dtype: int64
2.0    21
3.0    16
0.0     6
1.0     3
Name: Mortality national comparison, dtype: int64
2.0    14
1.0    14
3.0    13
0.0     5
Name: Safety of care national comparison, dtype: int64
1.0    25
2.0     8
3.0     8
0.0     5
Name: Readmission national comparison, dtype: int64
1.0    25
2.0    17
3.0     2
0.0     2
Name: Patient experience national comparison, dtype: int64
2.0    36
1.0     8
0.0     2
Name: Effectiveness of care national comparison, dtype: int64
1.0    27
2.0     8
0.0     8
3.0     3
Name: Timeliness of care national comparison, dtype: int64
2.0    18
0.0    14
1.0     9
3.0     5
Name: Efficient use of medical imaging national comparison, dtype: int64

In [43]:
hospital_rating_20=data_20[['Facility Name','Hospital overall rating','Mortality national comparison','Safety of care national comparison', 'Readmission national comparison','Patient experience national comparison','Effectiveness of care national comparison','Timeliness of care national comparison','Efficient use of medical imaging national comparison']].groupby('Facility Name').mean()
hospital_rating_20=hospital_rating_20.round(0)
for i in hospital_rating_20.columns:
    print(hospital_rating_20[i].value_counts())

2.0    9
3.0    7
4.0    6
0.0    1
Name: Hospital overall rating, dtype: int64
3    32
2    30
0    16
1     1
Name: Mortality national comparison, dtype: int64
3    31
1    27
2    11
0    10
Name: Safety of care national comparison, dtype: int64
1    40
3    16
0    12
2    11
Name: Readmission national comparison, dtype: int64
1    42
2    19
3    10
0     8
Name: Patient experience national comparison, dtype: int64
2    62
1     9
0     8
Name: Effectiveness of care national comparison, dtype: int64
1    45
0    17
2    13
3     4
Name: Timeliness of care national comparison, dtype: int64
2    36
0    33
3     6
1     4
Name: Efficient use of medical imaging national comparison, dtype: int64

In [44]:
hospital_rating_20.loc[hospital_rating_20['Hospital overall rating'] == 1]

Empty DataFrame
Columns: [Hospital overall rating, Mortality national comparison, Safety of care national comparison, Readmission national comparison, Patient experience national comparison, Effectiveness of care national comparison, Timeliness of care national comparison, Efficient use of medical imaging national comparison]
Index: []

In [45]:
hospital_rating_20.loc[hospital_rating_20['Hospital overall rating'] == 5]

Empty DataFrame
Columns: [Hospital overall rating, Mortality national comparison, Safety of care national comparison, Readmission national comparison, Patient experience national comparison, Effectiveness of care national comparison, Timeliness of care national comparison, Efficient use of medical imaging national comparison]
Index: []